Need to do appropriate fix
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'form-control ng-untouched ng-pristine ng-invalid'. Current value: 'form-control ng-pristine ng-invalid ng-touched'..

Find out more:
https://angular.io/errors/NG0100